### ISSUE TITLE
DEPRECATED: Enable your Nuxt project to use TypeScript easier and quicker 

### ISSUE THREAD

**Issue by JuanGrauGGG** [nuxt-community/hackernews-nuxt-ts#22]
According to https://github.com/hmsk/nuxt-ts , This package should no longer be used.
Moreover ts-lint should be removed in favour of eslint as it will be abandoned. (https://github.com/palantir/tslint)
Could this repo be updated? 
Do you need help to do so?

**Comment by kevinmarrec** [comment]
Overall I think this project need a revamp, but I don't have time for now to take care of it, any contribution is welcome.

**Comment by husayt** [comment]
Having started the project and created the repo, I was stripped of admin rights once I imported the project here. That set me off from continuing to contribute. I started it here because I thought this was community space, but this has not turned  as expected. 

Cc @nuxt-community/core-team

**Comment by atinux** [comment]
Maybe archiving this project? Cc @pi0

**Comment by pi0** [comment]
Agreed. We may finally migrate hackernews itself to typescript with improved support...
