### ISSUE TITLE
Unexpected identifier  "import"

### ISSUE THREAD

**Issue by yariksav** [nuxt-community/hackernews-nuxt-ts#6]
I've cloned repository and run "npm i", "npm run dev" and got this error
How can I heal this?
![image](https://user-images.githubusercontent.com/2553313/51637900-9ac0df00-1f65-11e9-8424-a907cb6d5ba0.png)

**Comment by husayt** [comment]
what version is your node/npm?

**Comment by husayt** [comment]
It's to do with latest nuxt-ts. We need to upgrade code to be compatible
with it or use previous version of nuxt ts.

**Comment by yariksav** [comment]
Ok, I will wait for upgrade nuxt-ts

**Comment by husayt** [comment]
Should be resolved with latest.
