### ISSUE TITLE
Missing @nuxt/typescript-edge

### ISSUE THREAD

**Issue by francoism90** [nuxt-community/hackernews-nuxt-ts#9]
Should this be installed globally or in this project?

**Comment by kevinmarrec** [comment]
@francoism90, `@nuxt/typescript-edge` is shipped with `nuxt-ts-edge`, you don't need further installation.

**Comment by kevinmarrec** [comment]
Your `package.json` might targeting not latest `nuxt-ts-edge`.

Your `node_modules` might be also corrupted.

Try removing it and be sure you're targeting last version of `nuxt-ts-edge` before doing `yarn install`

**Comment by francoism90** [comment]
@kevinmarrec I simple cloned the repo and run `yarn install`, no modifications whatsoever.

**Comment by kevinmarrec** [comment]
@francoism90 https://codesandbox.io/s/github/nuxt-community/hackernews-nuxt-ts is a mirror of this repo and is working fine.

**Comment by kevinmarrec** [comment]
Can you upload your `yarn.lock` file ?

**Comment by francoism90** [comment]
@kevinmarrec https://pastebin.com/2nPeFfn9

**Comment by kevinmarrec** [comment]
@francoism90 It's not last `nuxt-ts-edge`. Force the update to `2.4.0-25810574.3d0bc199` by replacing `latest` to this version in `package.json`, then remove `node_modules` && reinstall.

Your issue is cause in your version TypeScript can't find `node_modules/@nuxt/typescript-edge/tsconfig.json`.

**Comment by francoism90** [comment]
@kevinmarrec Thanks, that fixed the issue. :)

Should I change something in my config to prevent this from happening?

**Comment by kevinmarrec** [comment]
Nope, I'm gonna update the `yarn.lock` on the repository, seems to be maybe the issue.
CodeSandBox uses the `post-update` script that pull the last version of packages, so it ignores `yarn.lock`.
